
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Cart from "@/cart/page";
import SideAccordion from "@/accordian/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <>
        

        
      <body >
        
        {children}
        
        
        </body>
    
    </>
    
  );
}
